import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import './css/style.scss';
import Footer from "./components/Footer";
import Header from "./components/Header";
import localFont from 'next/font/local'

const inter = Inter({ subsets: ["latin"] });
const myFont = localFont({ src: './fonts/JosefinSans-Regular.ttf' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <Header />
       

        {children}
        <Footer/>
      </body>
    </html>
  );
}
