import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./css/style.scss";
import Footer from "./components/Footer";
import Header from "./components/Header";
import localFont from "next/font/local";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });
const myFont = localFont({ src: "./fonts/JosefinSans-Regular.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={myFont.className}>
        <Suspense>
          <Header />

          {children}
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
